#lang racket
(define (square a)
  (* a a)
  )
(define (sum-of-squares a b)
  (+ (square a) (square b))
  )
(define (f a b c)
  (cond ((and (< a b) (< a c)) (sum-of-squares b c))
        ((and (< b c) (< b a)) (sum-of-squares a c))
        (else (sum-of-squares a b))
    )
  )

(f 1 2 3)
